name: Run Unix Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -e .
          python -m pip install coverage
      - name: Run Tests
        run: |
          coverage run --source=. --omit=extended_train_test_split/__init__.py,setup.py,test/* -m unittest discover
      - name: Show Coverage
        run: |
          coverage report -m
